files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW
    translatable_elements:
      - /resources/string
